// Authentication
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const LOGOUT_USER = "LOGIN_LOGIN_OUTUSER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

// REGISTRATION
export const REQ_REGISTER = "REGISTER_USER";
export const REGISTER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_USER_FAILED";
